using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HardHorn.Archiving
{
    public class TiffTag
    {
        public enum TagNamespace
        {
            Baseline,
            Extension,
            Private,
            Exif,
            GPS,
            Interoperability
        }

        static readonly public IReadOnlyDictionary<ushort, TiffTag> TiffTags = new Dictionary<ushort, TiffTag>()
        {
            { 254, new TiffTag(TagNamespace.Baseline, 254, "NewSubfileType", "A general indication of the kind of data contained in this subfile.") },
            { 255, new TiffTag(TagNamespace.Baseline, 255, "SubfileType", "A general indication of the kind of data contained in this subfile.") },
            { 256, new TiffTag(TagNamespace.Baseline, 256, "ImageWidth", "The number of columns in the image, i.e., the number of pixels per row.") },
            { 257, new TiffTag(TagNamespace.Baseline, 257, "ImageLength", "The number of rows of pixels in the image.") },
            { 258, new TiffTag(TagNamespace.Baseline, 258, "BitsPerSample", "Number of bits per component.") },
            { 259, new TiffTag(TagNamespace.Baseline, 259, "Compression", "Compression scheme used on the image data.") },
            { 262, new TiffTag(TagNamespace.Baseline, 262, "PhotometricInterpretation", "The color space of the image data.") },
            { 263, new TiffTag(TagNamespace.Baseline, 263, "Threshholding", "For black and white TIFF files that represent shades of gray, the technique used to convert from gray to black and white pixels.") },
            { 264, new TiffTag(TagNamespace.Baseline, 264, "CellWidth", "The width of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.") },
            { 265, new TiffTag(TagNamespace.Baseline, 265, "CellLength", "The length of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.") },
            { 266, new TiffTag(TagNamespace.Baseline, 266, "FillOrder", "The logical order of bits within a byte.") },
            { 270, new TiffTag(TagNamespace.Baseline, 270, "ImageDescription", "A string that describes the subject of the image.") },
            { 271, new TiffTag(TagNamespace.Baseline, 271, "Make", "The scanner manufacturer.") },
            { 272, new TiffTag(TagNamespace.Baseline, 272, "Model", "The scanner model name or number.") },
            { 273, new TiffTag(TagNamespace.Baseline, 273, "StripOffsets", "For each strip, the byte offset of that strip.") },
            { 274, new TiffTag(TagNamespace.Baseline, 274, "Orientation", "The orientation of the image with respect to the rows and columns.") },
            { 277, new TiffTag(TagNamespace.Baseline, 277, "SamplesPerPixel", "The number of components per pixel.") },
            { 278, new TiffTag(TagNamespace.Baseline, 278, "RowsPerStrip", "The number of rows per strip.") },
            { 279, new TiffTag(TagNamespace.Baseline, 279, "StripByteCounts", "For each strip, the number of bytes in the strip after compression.") },
            { 280, new TiffTag(TagNamespace.Baseline, 280, "MinSampleValue", "The minimum component value used.") },
            { 281, new TiffTag(TagNamespace.Baseline, 281, "MaxSampleValue", "The maximum component value used.") },
            { 282, new TiffTag(TagNamespace.Baseline, 282, "XResolution", "The number of pixels per ResolutionUnit in the ImageWidth direction.") },
            { 283, new TiffTag(TagNamespace.Baseline, 283, "YResolution", "The number of pixels per ResolutionUnit in the ImageLength direction.") },
            { 284, new TiffTag(TagNamespace.Baseline, 284, "PlanarConfiguration", "How the components of each pixel are stored.") },
            { 288, new TiffTag(TagNamespace.Baseline, 288, "FreeOffsets", "For each string of contiguous unused bytes in a TIFF file, the byte offset of the string.") },
            { 289, new TiffTag(TagNamespace.Baseline, 289, "FreeByteCounts", "For each string of contiguous unused bytes in a TIFF file, the number of bytes in the string.") },
            { 290, new TiffTag(TagNamespace.Baseline, 290, "GrayResponseUnit", "The precision of the information contained in the GrayResponseCurve.") },
            { 291, new TiffTag(TagNamespace.Baseline, 291, "GrayResponseCurve", "For grayscale data, the optical density of each possible pixel value.") },
            { 296, new TiffTag(TagNamespace.Baseline, 296, "ResolutionUnit", "The unit of measurement for XResolution and YResolution.") },
            { 305, new TiffTag(TagNamespace.Baseline, 305, "Software", "Name and version number of the software package(s) used to create the image.") },
            { 306, new TiffTag(TagNamespace.Baseline, 306, "DateTime", "Date and time of image creation.") },
            { 315, new TiffTag(TagNamespace.Baseline, 315, "Artist", "Person who created the image.") },
            { 316, new TiffTag(TagNamespace.Baseline, 316, "HostComputer", "The computer and/or operating system in use at the time of image creation.") },
            { 320, new TiffTag(TagNamespace.Baseline, 320, "ColorMap", "A color map for palette color images.") },
            { 338, new TiffTag(TagNamespace.Baseline, 338, "ExtraSamples", "Description of extra components.") },
            { 33432, new TiffTag(TagNamespace.Baseline, 33432, "Copyright", "Copyright notice.") },

            { 269, new TiffTag(TagNamespace.Extension, 269, "DocumentName", "The name of the document from which this image was scanned.") },
            { 285, new TiffTag(TagNamespace.Extension, 285, "PageName", "The name of the page from which this image was scanned.") },
            { 286, new TiffTag(TagNamespace.Extension, 286, "XPosition", "X position of the image.") },
            { 287, new TiffTag(TagNamespace.Extension, 287, "YPosition", "Y position of the image.") },
            { 292, new TiffTag(TagNamespace.Extension, 292, "T4Options", "Options for Group 3 Fax compression") },
            { 293, new TiffTag(TagNamespace.Extension, 293, "T6Options", "Options for Group 4 Fax compression") },
            { 297, new TiffTag(TagNamespace.Extension, 297, "PageNumber", "The page number of the page from which this image was scanned.") },
            { 301, new TiffTag(TagNamespace.Extension, 301, "TransferFunction", "Describes a transfer function for the image in tabular style.") },
            { 317, new TiffTag(TagNamespace.Extension, 317, "Predictor", "A mathematical operator that is applied to the image data before an encoding scheme is applied.") },
            { 318, new TiffTag(TagNamespace.Extension, 318, "WhitePoint", "The chromaticity of the white point of the image.") },
            { 319, new TiffTag(TagNamespace.Extension, 319, "PrimaryChromaticities", "The chromaticities of the primaries of the image.") },
            { 321, new TiffTag(TagNamespace.Extension, 321, "HalftoneHints", "Conveys to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail.") },
            { 322, new TiffTag(TagNamespace.Extension, 322, "TileWidth", "The tile width in pixels. This is the number of columns in each tile.") },
            { 323, new TiffTag(TagNamespace.Extension, 323, "TileLength", "The tile length (height) in pixels. This is the number of rows in each tile.") },
            { 324, new TiffTag(TagNamespace.Extension, 324, "TileOffsets", "For each tile, the byte offset of that tile, as compressed and stored on disk.") },
            { 325, new TiffTag(TagNamespace.Extension, 325, "TileByteCounts", "For each tile, the number of (compressed) bytes in that tile.") },
            { 326, new TiffTag(TagNamespace.Extension, 326, "BadFaxLines", "Used in the TIFF-F standard, denotes the number of 'bad' scan lines encountered by the facsimile device.") },
            { 327, new TiffTag(TagNamespace.Extension, 327, "CleanFaxData", "Used in the TIFF-F standard, indicates if 'bad' lines encountered during reception are stored in the data, or if 'bad' lines have been replaced by the receiver.") },
            { 328, new TiffTag(TagNamespace.Extension, 328, "ConsecutiveBadFaxLines", "Used in the TIFF-F standard, denotes the maximum number of consecutive 'bad' scanlines received.") },
            { 330, new TiffTag(TagNamespace.Extension, 330, "SubIFDs", "Offset to child IFDs.") },
            { 332, new TiffTag(TagNamespace.Extension, 332, "InkSet", "The set of inks used in a separated (PhotometricInterpretation=5) image.") },
            { 333, new TiffTag(TagNamespace.Extension, 333, "InkNames", "The name of each ink used in a separated image.") },
            { 334, new TiffTag(TagNamespace.Extension, 334, "NumberOfInks", "The number of inks.") },
            { 336, new TiffTag(TagNamespace.Extension, 336, "DotRange", "The component values that correspond to a 0% dot and 100% dot.") },
            { 337, new TiffTag(TagNamespace.Extension, 337, "TargetPrinter", "A description of the printing environment for which this separation is intended.") },
            { 339, new TiffTag(TagNamespace.Extension, 339, "SampleFormat", "Specifies how to interpret each data sample in a pixel.") },
            { 340, new TiffTag(TagNamespace.Extension, 340, "SMinSampleValue", "Specifies the minimum sample value.") },
            { 341, new TiffTag(TagNamespace.Extension, 341, "SMaxSampleValue", "Specifies the maximum sample value.") },
            { 342, new TiffTag(TagNamespace.Extension, 342, "TransferRange", "Expands the range of the TransferFunction.") },
            { 343, new TiffTag(TagNamespace.Extension, 343, "ClipPath", "Mirrors the essentials of PostScript's path creation functionality.") },
            { 344, new TiffTag(TagNamespace.Extension, 344, "XClipPathUnits", "The number of units that span the width of the image, in terms of integer ClipPath coordinates.") },
            { 345, new TiffTag(TagNamespace.Extension, 345, "YClipPathUnits", "The number of units that span the height of the image, in terms of integer ClipPath coordinates.") },
            { 346, new TiffTag(TagNamespace.Extension, 346, "Indexed", "Aims to broaden the support for indexed images to include support for any color space.") },
            { 347, new TiffTag(TagNamespace.Extension, 347, "JPEGTables", "JPEG quantization and/or Huffman tables.") },
            { 351, new TiffTag(TagNamespace.Extension, 351, "OPIProxy", "OPI-related.") },
            { 400, new TiffTag(TagNamespace.Extension, 400, "GlobalParametersIFD", "Used in the TIFF-FX standard to point to an IFD containing tags that are globally applicable to the complete TIFF file.") },
            { 401, new TiffTag(TagNamespace.Extension, 401, "ProfileType", "Used in the TIFF-FX standard, denotes the type of data stored in this file or IFD.") },
            { 402, new TiffTag(TagNamespace.Extension, 402, "FaxProfile", "Used in the TIFF-FX standard, denotes the 'profile' that applies to this file.") },
            { 403, new TiffTag(TagNamespace.Extension, 403, "CodingMethods", "Used in the TIFF-FX standard, indicates which coding methods are used in the file.") },
            { 404, new TiffTag(TagNamespace.Extension, 404, "VersionYear", "Used in the TIFF-FX standard, denotes the year of the standard specified by the FaxProfile field.") },
            { 405, new TiffTag(TagNamespace.Extension, 405, "ModeNumber", "Used in the TIFF-FX standard, denotes the mode of the standard specified by the FaxProfile field.") },
            { 433, new TiffTag(TagNamespace.Extension, 433, "Decode", "Used in the TIFF-F and TIFF-FX standards, holds information about the ITULAB (PhotometricInterpretation = 10) encoding.") },
            { 434, new TiffTag(TagNamespace.Extension, 434, "DefaultImageColor", "Defined in the Mixed Raster Content part of RFC 2301, is the default color needed in areas where no image is available.") },
            { 512, new TiffTag(TagNamespace.Extension, 512, "JPEGProc", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 513, new TiffTag(TagNamespace.Extension, 513, "JPEGInterchangeFormat", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 514, new TiffTag(TagNamespace.Extension, 514, "JPEGInterchangeFormatLength", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 515, new TiffTag(TagNamespace.Extension, 515, "JPEGRestartInterval", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 517, new TiffTag(TagNamespace.Extension, 517, "JPEGLosslessPredictors", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 518, new TiffTag(TagNamespace.Extension, 518, "JPEGPointTransforms", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 519, new TiffTag(TagNamespace.Extension, 519, "JPEGQTables", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 520, new TiffTag(TagNamespace.Extension, 520, "JPEGDCTables", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 521, new TiffTag(TagNamespace.Extension, 521, "JPEGACTables", "Old-style JPEG compression field. TechNote2 invalidates this part of the specification.") },
            { 529, new TiffTag(TagNamespace.Extension, 529, "YCbCrCoefficients", "The transformation from RGB to YCbCr image data.") },
            { 530, new TiffTag(TagNamespace.Extension, 530, "YCbCrSubSampling", "Specifies the subsampling factors used for the chrominance components of a YCbCr image.") },
            { 531, new TiffTag(TagNamespace.Extension, 531, "YCbCrPositioning", "Specifies the positioning of subsampled chrominance components relative to luminance samples.") },
            { 532, new TiffTag(TagNamespace.Extension, 532, "ReferenceBlackWhite", "Specifies a pair of headroom and footroom image data values (codes) for each pixel component.") },
            { 559, new TiffTag(TagNamespace.Extension, 559, "StripRowCounts", "Defined in the Mixed Raster Content part of RFC 2301, used to replace RowsPerStrip for IFDs with variable-sized strips.") },
            { 700, new TiffTag(TagNamespace.Extension, 700, "XMP", "XML packet containing XMP metadata") },
            { 32781, new TiffTag(TagNamespace.Extension, 32781, "ImageID", "OPI-related.") },
            { 34732, new TiffTag(TagNamespace.Extension, 34732, "ImageLayer", "Defined in the Mixed Raster Content part of RFC 2301, used to denote the particular function of this Image in the mixed raster scheme.") },

            { 32932, new TiffTag(TagNamespace.Private, 32932, "Wang Annotation", "Annotation data, as used in 'Imaging for Windows'.") },
            { 33445, new TiffTag(TagNamespace.Private, 33445, "MD FileTag", "Specifies the pixel data format encoding in the Molecular Dynamics GEL file format.") },
            { 33446, new TiffTag(TagNamespace.Private, 33446, "MD ScalePixel", "Specifies a scale factor in the Molecular Dynamics GEL file format.") },
            { 33447, new TiffTag(TagNamespace.Private, 33447, "MD ColorTable", "Used to specify the conversion from 16bit to 8bit in the Molecular Dynamics GEL file format.") },
            { 33448, new TiffTag(TagNamespace.Private, 33448, "MD LabName", "Name of the lab that scanned this file, as used in the Molecular Dynamics GEL file format.") },
            { 33449, new TiffTag(TagNamespace.Private, 33449, "MD SampleInfo", "Information about the sample, as used in the Molecular Dynamics GEL file format.") },
            { 33450, new TiffTag(TagNamespace.Private, 33450, "MD PrepDate", "Date the sample was prepared, as used in the Molecular Dynamics GEL file format.") },
            { 33451, new TiffTag(TagNamespace.Private, 33451, "MD PrepTime", "Time the sample was prepared, as used in the Molecular Dynamics GEL file format.") },
            { 33452, new TiffTag(TagNamespace.Private, 33452, "MD FileUnits", "Units for data in this file, as used in the Molecular Dynamics GEL file format.") },
            { 33550, new TiffTag(TagNamespace.Private, 33550, "ModelPixelScaleTag", "Used in interchangeable GeoTIFF files.") },
            { 33723, new TiffTag(TagNamespace.Private, 33723, "IPTC", "IPTC (International Press Telecommunications Council) metadata.") },
            { 33918, new TiffTag(TagNamespace.Private, 33918, "INGR Packet Data Tag", "Intergraph Application specific storage.") },
            { 33919, new TiffTag(TagNamespace.Private, 33919, "INGR Flag Registers", "Intergraph Application specific flags.") },
            { 33920, new TiffTag(TagNamespace.Private, 33920, "IrasB Transformation Matrix", "Originally part of Intergraph's GeoTIFF tags, but likely understood by IrasB only.") },
            { 33922, new TiffTag(TagNamespace.Private, 33922, "ModelTiepointTag", "Originally part of Intergraph's GeoTIFF tags, but now used in interchangeable GeoTIFF files.") },
            { 34264, new TiffTag(TagNamespace.Private, 34264, "ModelTransformationTag", "Used in interchangeable GeoTIFF files.") },
            { 34377, new TiffTag(TagNamespace.Private, 34377, "Photoshop", "Collection of Photoshop 'Image Resource Blocks'.") },
            { 34665, new TiffTag(TagNamespace.Private, 34665, "Exif IFD", "A pointer to the Exif IFD.") },
            { 34675, new TiffTag(TagNamespace.Private, 34675, "ICC Profile", "ICC profile data.") },
            { 34735, new TiffTag(TagNamespace.Private, 34735, "GeoKeyDirectoryTag", "Used in interchangeable GeoTIFF files.") },
            { 34736, new TiffTag(TagNamespace.Private, 34736, "GeoDoubleParamsTag", "Used in interchangeable GeoTIFF files.") },
            { 34737, new TiffTag(TagNamespace.Private, 34737, "GeoAsciiParamsTag", "Used in interchangeable GeoTIFF files.") },
            { 34853, new TiffTag(TagNamespace.Private, 34853, "GPS IFD", "A pointer to the Exif-related GPS Info IFD.") },
            { 34908, new TiffTag(TagNamespace.Private, 34908, "HylaFAX FaxRecvParams", "Used by HylaFAX.") },
            { 34909, new TiffTag(TagNamespace.Private, 34909, "HylaFAX FaxSubAddress", "Used by HylaFAX.") },
            { 34910, new TiffTag(TagNamespace.Private, 34910, "HylaFAX FaxRecvTime", "Used by HylaFAX.") },
            { 37724, new TiffTag(TagNamespace.Private, 37724, "ImageSourceData", "Used by Adobe Photoshop.") },
            { 40965, new TiffTag(TagNamespace.Private, 40965, "Interoperability IFD", "A pointer to the Exif-related Interoperability IFD.") },
            { 42112, new TiffTag(TagNamespace.Private, 42112, "GDAL_METADATA", "Used by the GDAL library, holds an XML list of name=value 'metadata' values about the image as a whole, and about specific samples.") },
            { 42113, new TiffTag(TagNamespace.Private, 42113, "GDAL_NODATA", "Used by the GDAL library, contains an ASCII encoded nodata or background pixel value.") },
            { 50215, new TiffTag(TagNamespace.Private, 50215, "Oce Scanjob Description", "Used in the Oce scanning process.") },
            { 50216, new TiffTag(TagNamespace.Private, 50216, "Oce Application Selector", "Used in the Oce scanning process.") },
            { 50217, new TiffTag(TagNamespace.Private, 50217, "Oce Identification Number", "Used in the Oce scanning process.") },
            { 50218, new TiffTag(TagNamespace.Private, 50218, "Oce ImageLogic Characteristics", "Used in the Oce scanning process.") },
            { 50706, new TiffTag(TagNamespace.Private, 50706, "DNGVersion", "Used in IFD 0 of DNG files.") },
            { 50707, new TiffTag(TagNamespace.Private, 50707, "DNGBackwardVersion", "Used in IFD 0 of DNG files.") },
            { 50708, new TiffTag(TagNamespace.Private, 50708, "UniqueCameraModel", "Used in IFD 0 of DNG files.") },
            { 50709, new TiffTag(TagNamespace.Private, 50709, "LocalizedCameraModel", "Used in IFD 0 of DNG files.") },
            { 50710, new TiffTag(TagNamespace.Private, 50710, "CFAPlaneColor", "Used in Raw IFD of DNG files.") },
            { 50711, new TiffTag(TagNamespace.Private, 50711, "CFALayout", "Used in Raw IFD of DNG files.") },
            { 50712, new TiffTag(TagNamespace.Private, 50712, "LinearizationTable", "Used in Raw IFD of DNG files.") },
            { 50713, new TiffTag(TagNamespace.Private, 50713, "BlackLevelRepeatDim", "Used in Raw IFD of DNG files.") },
            { 50714, new TiffTag(TagNamespace.Private, 50714, "BlackLevel", "Used in Raw IFD of DNG files.") },
            { 50715, new TiffTag(TagNamespace.Private, 50715, "BlackLevelDeltaH", "Used in Raw IFD of DNG files.") },
            { 50716, new TiffTag(TagNamespace.Private, 50716, "BlackLevelDeltaV", "Used in Raw IFD of DNG files.") },
            { 50717, new TiffTag(TagNamespace.Private, 50717, "WhiteLevel", "Used in Raw IFD of DNG files.") },
            { 50718, new TiffTag(TagNamespace.Private, 50718, "DefaultScale", "Used in Raw IFD of DNG files.") },
            { 50719, new TiffTag(TagNamespace.Private, 50719, "DefaultCropOrigin", "Used in Raw IFD of DNG files.") },
            { 50720, new TiffTag(TagNamespace.Private, 50720, "DefaultCropSize", "Used in Raw IFD of DNG files.") },
            { 50721, new TiffTag(TagNamespace.Private, 50721, "ColorMatrix1", "Used in IFD 0 of DNG files.") },
            { 50722, new TiffTag(TagNamespace.Private, 50722, "ColorMatrix2", "Used in IFD 0 of DNG files.") },
            { 50723, new TiffTag(TagNamespace.Private, 50723, "CameraCalibration1", "Used in IFD 0 of DNG files.") },
            { 50724, new TiffTag(TagNamespace.Private, 50724, "CameraCalibration2", "Used in IFD 0 of DNG files.") },
            { 50725, new TiffTag(TagNamespace.Private, 50725, "ReductionMatrix1", "Used in IFD 0 of DNG files.") },
            { 50726, new TiffTag(TagNamespace.Private, 50726, "ReductionMatrix2", "Used in IFD 0 of DNG files.") },
            { 50727, new TiffTag(TagNamespace.Private, 50727, "AnalogBalance", "Used in IFD 0 of DNG files.") },
            { 50728, new TiffTag(TagNamespace.Private, 50728, "AsShotNeutral", "Used in IFD 0 of DNG files.") },
            { 50729, new TiffTag(TagNamespace.Private, 50729, "AsShotWhiteXY", "Used in IFD 0 of DNG files.") },
            { 50730, new TiffTag(TagNamespace.Private, 50730, "BaselineExposure", "Used in IFD 0 of DNG files.") },
            { 50731, new TiffTag(TagNamespace.Private, 50731, "BaselineNoise", "Used in IFD 0 of DNG files.") },
            { 50732, new TiffTag(TagNamespace.Private, 50732, "BaselineSharpness", "Used in IFD 0 of DNG files.") },
            { 50733, new TiffTag(TagNamespace.Private, 50733, "BayerGreenSplit", "Used in Raw IFD of DNG files.") },
            { 50734, new TiffTag(TagNamespace.Private, 50734, "LinearResponseLimit", "Used in IFD 0 of DNG files.") },
            { 50735, new TiffTag(TagNamespace.Private, 50735, "CameraSerialNumber", "Used in IFD 0 of DNG files.") },
            { 50736, new TiffTag(TagNamespace.Private, 50736, "LensInfo", "Used in IFD 0 of DNG files.") },
            { 50737, new TiffTag(TagNamespace.Private, 50737, "ChromaBlurRadius", "Used in Raw IFD of DNG files.") },
            { 50738, new TiffTag(TagNamespace.Private, 50738, "AntiAliasStrength", "Used in Raw IFD of DNG files.") },
            { 50740, new TiffTag(TagNamespace.Private, 50740, "DNGPrivateData", "Used in IFD 0 of DNG files.") },
            { 50741, new TiffTag(TagNamespace.Private, 50741, "MakerNoteSafety", "Used in IFD 0 of DNG files.") },
            { 50778, new TiffTag(TagNamespace.Private, 50778, "CalibrationIlluminant1", "Used in IFD 0 of DNG files.") },
            { 50779, new TiffTag(TagNamespace.Private, 50779, "CalibrationIlluminant2", "Used in IFD 0 of DNG files.") },
            { 50780, new TiffTag(TagNamespace.Private, 50780, "BestQualityScale", "Used in Raw IFD of DNG files.") },
            { 50784, new TiffTag(TagNamespace.Private, 50784, "Alias Layer Metadata", "Alias Sketchbook Pro layer usage description.") },
            { 50908, new TiffTag(TagNamespace.Private, 50908, "TIFF_RSID", "This private tag is used in a GEOTIFF standard by DGIWG.") },
            { 50909, new TiffTag(TagNamespace.Private, 50909, "GEO_METADATA", "This private tag is used in a GEOTIFF standard by DGIWG.") }
        };

        public static readonly IReadOnlyDictionary<ushort, TiffTag> ExifTags = new Dictionary<ushort, TiffTag>()
        {
            { 33434, new TiffTag(TagNamespace.Exif, 33434, "ExposureTime", "Exposure time, given in seconds.") },
            { 33437, new TiffTag(TagNamespace.Exif, 33437, "FNumber", "The F number.") },
            { 34850, new TiffTag(TagNamespace.Exif, 34850, "ExposureProgram", "The class of the program used by the camera to set exposure when the picture is taken.") },
            { 34852, new TiffTag(TagNamespace.Exif, 34852, "SpectralSensitivity", "Indicates the spectral sensitivity of each channel of the camera used.") },
            { 34855, new TiffTag(TagNamespace.Exif, 34855, "ISOSpeedRatings", "Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.") },
            { 34856, new TiffTag(TagNamespace.Exif, 34856, "OECF", "Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.") },
            { 36864, new TiffTag(TagNamespace.Exif, 36864, "ExifVersion", "The version of the supported Exif standard.") },
            { 36867, new TiffTag(TagNamespace.Exif, 36867, "DateTimeOriginal", "The date and time when the original image data was generated.") },
            { 36868, new TiffTag(TagNamespace.Exif, 36868, "DateTimeDigitized", "The date and time when the image was stored as digital data.") },
            { 37121, new TiffTag(TagNamespace.Exif, 37121, "ComponentsConfiguration", "Specific to compressed data; specifies the channels and complements PhotometricInterpretation") },
            { 37122, new TiffTag(TagNamespace.Exif, 37122, "CompressedBitsPerPixel", "Specific to compressed data; states the compressed bits per pixel.") },
            { 37377, new TiffTag(TagNamespace.Exif, 37377, "ShutterSpeedValue", "Shutter speed.") },
            { 37378, new TiffTag(TagNamespace.Exif, 37378, "ApertureValue", "The lens aperture.") },
            { 37379, new TiffTag(TagNamespace.Exif, 37379, "BrightnessValue", "The value of brightness.") },
            { 37380, new TiffTag(TagNamespace.Exif, 37380, "ExposureBiasValue", "The exposure bias.") },
            { 37381, new TiffTag(TagNamespace.Exif, 37381, "MaxApertureValue", "The smallest F number of the lens.") },
            { 37382, new TiffTag(TagNamespace.Exif, 37382, "SubjectDistance", "The distance to the subject, given in meters.") },
            { 37383, new TiffTag(TagNamespace.Exif, 37383, "MeteringMode", "The metering mode.") },
            { 37384, new TiffTag(TagNamespace.Exif, 37384, "LightSource", "The kind of light source.") },
            { 37385, new TiffTag(TagNamespace.Exif, 37385, "Flash", "Indicates the status of flash when the image was shot.") },
            { 37386, new TiffTag(TagNamespace.Exif, 37386, "FocalLength", "The actual focal length of the lens, in mm.") },
            { 37396, new TiffTag(TagNamespace.Exif, 37396, "SubjectArea", "Indicates the location and area of the main subject in the overall scene.") },
            { 37500, new TiffTag(TagNamespace.Exif, 37500, "MakerNote", "Manufacturer specific information.") },
            { 37510, new TiffTag(TagNamespace.Exif, 37510, "UserComment", "Keywords or comments on the image; complements ImageDescription.") },
            { 37520, new TiffTag(TagNamespace.Exif, 37520, "SubsecTime", "A tag used to record fractions of seconds for the DateTime tag.") },
            { 37521, new TiffTag(TagNamespace.Exif, 37521, "SubsecTimeOriginal", "A tag used to record fractions of seconds for the DateTimeOriginal tag.") },
            { 37522, new TiffTag(TagNamespace.Exif, 37522, "SubsecTimeDigitized", "A tag used to record fractions of seconds for the DateTimeDigitized tag.") },
            { 40960, new TiffTag(TagNamespace.Exif, 40960, "FlashpixVersion", "The Flashpix format version supported by a FPXR file.") },
            { 40961, new TiffTag(TagNamespace.Exif, 40961, "ColorSpace", "The color space information tag is always recorded as the color space specifier.") },
            { 40962, new TiffTag(TagNamespace.Exif, 40962, "PixelXDimension", "Specific to compressed data; the valid width of the meaningful image.") },
            { 40963, new TiffTag(TagNamespace.Exif, 40963, "PixelYDimension", "Specific to compressed data; the valid height of the meaningful image.") },
            { 40964, new TiffTag(TagNamespace.Exif, 40964, "RelatedSoundFile", "Used to record the name of an audio file related to the image data.") },
            { 41483, new TiffTag(TagNamespace.Exif, 41483, "FlashEnergy", "Indicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds") },
            { 41484, new TiffTag(TagNamespace.Exif, 41484, "SpatialFrequencyResponse", "Records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.") },
            { 41486, new TiffTag(TagNamespace.Exif, 41486, "FocalPlaneXResolution", "Indicates the number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.") },
            { 41487, new TiffTag(TagNamespace.Exif, 41487, "FocalPlaneYResolution", "Indicates the number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.") },
            { 41488, new TiffTag(TagNamespace.Exif, 41488, "FocalPlaneResolutionUnit", "Indicates the unit for measuring FocalPlaneXResolution and FocalPlaneYResolution.") },
            { 41492, new TiffTag(TagNamespace.Exif, 41492, "SubjectLocation", "Indicates the location of the main subject in the scene.") },
            { 41493, new TiffTag(TagNamespace.Exif, 41493, "ExposureIndex", "Indicates the exposure index selected on the camera or input device at the time the image is captured.") },
            { 41495, new TiffTag(TagNamespace.Exif, 41495, "SensingMethod", "Indicates the image sensor type on the camera or input device.") },
            { 41728, new TiffTag(TagNamespace.Exif, 41728, "FileSource", "Indicates the image source.") },
            { 41729, new TiffTag(TagNamespace.Exif, 41729, "SceneType", "Indicates the type of scene.") },
            { 41730, new TiffTag(TagNamespace.Exif, 41730, "CFAPattern", "Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used.") },
            { 41985, new TiffTag(TagNamespace.Exif, 41985, "CustomRendered", "Indicates the use of special processing on image data, such as rendering geared to output.") },
            { 41986, new TiffTag(TagNamespace.Exif, 41986, "ExposureMode", "Indicates the exposure mode set when the image was shot.") },
            { 41987, new TiffTag(TagNamespace.Exif, 41987, "WhiteBalance", "Indicates the white balance mode set when the image was shot.") },
            { 41988, new TiffTag(TagNamespace.Exif, 41988, "DigitalZoomRatio", "Indicates the digital zoom ratio when the image was shot.") },
            { 41989, new TiffTag(TagNamespace.Exif, 41989, "FocalLengthIn35mmFilm", "Indicates the equivalent focal length assuming a 35mm film camera, in mm.") },
            { 41990, new TiffTag(TagNamespace.Exif, 41990, "SceneCaptureType", "Indicates the type of scene that was shot.") },
            { 41991, new TiffTag(TagNamespace.Exif, 41991, "GainControl", "Indicates the degree of overall image gain adjustment.") },
            { 41992, new TiffTag(TagNamespace.Exif, 41992, "Contrast", "Indicates the direction of contrast processing applied by the camera when the image was shot.") },
            { 41993, new TiffTag(TagNamespace.Exif, 41993, "Saturation", "Indicates the direction of saturation processing applied by the camera when the image was shot.") },
            { 41994, new TiffTag(TagNamespace.Exif, 41994, "Sharpness", "Indicates the direction of sharpness processing applied by the camera when the image was shot.") },
            { 41995, new TiffTag(TagNamespace.Exif, 41995, "DeviceSettingDescription", "This tag indicates information on the picture-taking conditions of a particular camera model.") },
            { 41996, new TiffTag(TagNamespace.Exif, 41996, "SubjectDistanceRange", "Indicates the distance to the subject.") },
            { 42016, new TiffTag(TagNamespace.Exif, 42016, "ImageUniqueID", "Indicates an identifier assigned uniquely to each image.") }
        };

        public static readonly IReadOnlyDictionary<ushort, TiffTag> ExifGPSTags = new Dictionary<ushort, TiffTag>()
        {
            { 0, new TiffTag(TagNamespace.GPS, 0, "GPSVersionID", "Indicates the version of GPSInfoIFD.") },
            { 1, new TiffTag(TagNamespace.GPS, 1, "GPSLatitudeRef", "Indicates whether the latitude is north or south latitude.") },
            { 2, new TiffTag(TagNamespace.GPS, 2, "GPSLatitude", "Indicates the latitude.") },
            { 3, new TiffTag(TagNamespace.GPS, 3, "GPSLongitudeRef", "Indicates whether the longitude is east or west longitude.") },
            { 4, new TiffTag(TagNamespace.GPS, 4, "GPSLongitude", "Indicates the longitude.") },
            { 5, new TiffTag(TagNamespace.GPS, 5, "GPSAltitudeRef", "Indicates the altitude used as the reference altitude.") },
            { 6, new TiffTag(TagNamespace.GPS, 6, "GPSAltitude", "Indicates the altitude based on the reference in GPSAltitudeRef.") },
            { 7, new TiffTag(TagNamespace.GPS, 7, "GPSTimeStamp", "Indicates the time as UTC (Coordinated Universal Time).") },
            { 8, new TiffTag(TagNamespace.GPS, 8, "GPSSatellites", "Indicates the GPS satellites used for measurements.") },
            { 9, new TiffTag(TagNamespace.GPS, 9, "GPSStatus", "Indicates the status of the GPS receiver when the image is recorded.") },
            { 10, new TiffTag(TagNamespace.GPS, 10, "GPSMeasureMode", "Indicates the GPS measurement mode.") },
            { 11, new TiffTag(TagNamespace.GPS, 11, "GPSDOP", "Indicates the GPS DOP (data degree of precision).") },
            { 12, new TiffTag(TagNamespace.GPS, 12, "GPSSpeedRef", "Indicates the unit used to express the GPS receiver speed of movement.") },
            { 13, new TiffTag(TagNamespace.GPS, 13, "GPSSpeed", "Indicates the speed of GPS receiver movement.") },
            { 14, new TiffTag(TagNamespace.GPS, 14, "GPSTrackRef", "Indicates the reference for giving the direction of GPS receiver movement.") },
            { 15, new TiffTag(TagNamespace.GPS, 15, "GPSTrack", "Indicates the direction of GPS receiver movement.") },
            { 16, new TiffTag(TagNamespace.GPS, 16, "GPSImgDirectionRef", "Indicates the reference for giving the direction of the image when it is captured.") },
            { 17, new TiffTag(TagNamespace.GPS, 17, "GPSImgDirection", "Indicates the direction of the image when it was captured.") },
            { 18, new TiffTag(TagNamespace.GPS, 18, "GPSMapDatum", "Indicates the geodetic survey data used by the GPS receiver.") },
            { 19, new TiffTag(TagNamespace.GPS, 19, "GPSDestLatitudeRef", "Indicates whether the latitude of the destination point is north or south latitude.") },
            { 20, new TiffTag(TagNamespace.GPS, 20, "GPSDestLatitude", "Indicates the latitude of the destination point.") },
            { 21, new TiffTag(TagNamespace.GPS, 21, "GPSDestLongitudeRef", "Indicates whether the longitude of the destination point is east or west longitude.") },
            { 22, new TiffTag(TagNamespace.GPS, 22, "GPSDestLongitude", "Indicates the longitude of the destination point.") },
            { 23, new TiffTag(TagNamespace.GPS, 23, "GPSDestBearingRef", "Indicates the reference used for giving the bearing to the destination point.") },
            { 24, new TiffTag(TagNamespace.GPS, 24, "GPSDestBearing", "Indicates the bearing to the destination point.") },
            { 25, new TiffTag(TagNamespace.GPS, 25, "GPSDestDistanceRef", "Indicates the unit used to express the distance to the destination point.") },
            { 26, new TiffTag(TagNamespace.GPS, 26, "GPSDestDistance", "Indicates the distance to the destination point.") },
            { 27, new TiffTag(TagNamespace.GPS, 27, "GPSProcessingMethod", "A character string recording the name of the method used for location finding.") },
            { 28, new TiffTag(TagNamespace.GPS, 28, "GPSAreaInformation", "A character string recording the name of the GPS area.") },
            { 29, new TiffTag(TagNamespace.GPS, 29, "GPSDateStamp", "A character string recording date and time information relative to UTC (Coordinated Universal Time).") },
            { 30, new TiffTag(TagNamespace.GPS, 30, "GPSDifferential", "Indicates whether differential correction is applied to the GPS receiver.") }
        };

        public static readonly IReadOnlyDictionary<ushort, TiffTag> ExifInteroperabilityTags = new Dictionary<ushort, TiffTag>()
        {
            {1, new TiffTag(TagNamespace.Interoperability, 1, "InteroperabilityIndex", "Indicates the identification of the Interoperability rule.") }
        };

        public TagNamespace Namespace { get; private set; }
        public ISet<TiffType> AllowedTypes { get; private set; }
        public string Name { get; private set; }
        public ushort Code { get; private set; }
        public string Description { get; private set; }

        public TiffTag(TagNamespace ns, ushort code, string name, string description)
        {
            Namespace = ns;
            Name = name;
            Code = code;
            Description = description;
        }

        public override string ToString()
        {
            return $"{{TiffTag {Namespace.ToString()}:{Name}}}";
        }
    }
}
