//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NEA.ArchiveModel.BKG1007 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0", IsNullable=false)]
    public partial class archiveIndex {
        
        private string archiveInformationPackageIDField;
        
        private string archiveInformationPackageIDPreviousField;
        
        private string archivePeriodStartField;
        
        private string archivePeriodEndField;
        
        private bool archiveInformationPacketTypeField;
        
        private archiveIndexArchiveCreatorList archiveCreatorListField;
        
        private bool archiveTypeField;
        
        private string systemNameField;
        
        private string[] alternativeNameField;
        
        private string systemPurposeField;
        
        private string systemContentField;
        
        private bool regionNumField;
        
        private bool komNumField;
        
        private bool cprNumField;
        
        private bool cvrNumField;
        
        private bool matrikNumField;
        
        private bool bbrNumField;
        
        private bool whoSygKodField;
        
        private string[] sourceNameField;
        
        private string[] userNameField;
        
        private string[] predecessorNameField;
        
        private archiveIndexForm formField;
        
        private bool containsDigitalDocumentsField;
        
        private bool searchRelatedOtherRecordsField;
        
        private string[] relatedRecordsNameField;
        
        private bool systemFileConceptField;
        
        private bool multipleDataCollectionField;
        
        private bool personalDataRestrictedInfoField;
        
        private bool otherAccessTypeRestrictionsField;
        
        private string archiveApprovalField;
        
        private string archiveRestrictionsField;
        
        /// <remarks/>
        public string archiveInformationPackageID {
            get {
                return this.archiveInformationPackageIDField;
            }
            set {
                this.archiveInformationPackageIDField = value;
            }
        }
        
        /// <remarks/>
        public string archiveInformationPackageIDPrevious {
            get {
                return this.archiveInformationPackageIDPreviousField;
            }
            set {
                this.archiveInformationPackageIDPreviousField = value;
            }
        }
        
        /// <remarks/>
        public string archivePeriodStart {
            get {
                return this.archivePeriodStartField;
            }
            set {
                this.archivePeriodStartField = value;
            }
        }
        
        /// <remarks/>
        public string archivePeriodEnd {
            get {
                return this.archivePeriodEndField;
            }
            set {
                this.archivePeriodEndField = value;
            }
        }
        
        /// <remarks/>
        public bool archiveInformationPacketType {
            get {
                return this.archiveInformationPacketTypeField;
            }
            set {
                this.archiveInformationPacketTypeField = value;
            }
        }
        
        /// <remarks/>
        public archiveIndexArchiveCreatorList archiveCreatorList {
            get {
                return this.archiveCreatorListField;
            }
            set {
                this.archiveCreatorListField = value;
            }
        }
        
        /// <remarks/>
        public bool archiveType {
            get {
                return this.archiveTypeField;
            }
            set {
                this.archiveTypeField = value;
            }
        }
        
        /// <remarks/>
        public string systemName {
            get {
                return this.systemNameField;
            }
            set {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alternativeName")]
        public string[] alternativeName {
            get {
                return this.alternativeNameField;
            }
            set {
                this.alternativeNameField = value;
            }
        }
        
        /// <remarks/>
        public string systemPurpose {
            get {
                return this.systemPurposeField;
            }
            set {
                this.systemPurposeField = value;
            }
        }
        
        /// <remarks/>
        public string systemContent {
            get {
                return this.systemContentField;
            }
            set {
                this.systemContentField = value;
            }
        }
        
        /// <remarks/>
        public bool regionNum {
            get {
                return this.regionNumField;
            }
            set {
                this.regionNumField = value;
            }
        }
        
        /// <remarks/>
        public bool komNum {
            get {
                return this.komNumField;
            }
            set {
                this.komNumField = value;
            }
        }
        
        /// <remarks/>
        public bool cprNum {
            get {
                return this.cprNumField;
            }
            set {
                this.cprNumField = value;
            }
        }
        
        /// <remarks/>
        public bool cvrNum {
            get {
                return this.cvrNumField;
            }
            set {
                this.cvrNumField = value;
            }
        }
        
        /// <remarks/>
        public bool matrikNum {
            get {
                return this.matrikNumField;
            }
            set {
                this.matrikNumField = value;
            }
        }
        
        /// <remarks/>
        public bool bbrNum {
            get {
                return this.bbrNumField;
            }
            set {
                this.bbrNumField = value;
            }
        }
        
        /// <remarks/>
        public bool whoSygKod {
            get {
                return this.whoSygKodField;
            }
            set {
                this.whoSygKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sourceName")]
        public string[] sourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userName")]
        public string[] userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("predecessorName")]
        public string[] predecessorName {
            get {
                return this.predecessorNameField;
            }
            set {
                this.predecessorNameField = value;
            }
        }
        
        /// <remarks/>
        public archiveIndexForm form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
        
        /// <remarks/>
        public bool containsDigitalDocuments {
            get {
                return this.containsDigitalDocumentsField;
            }
            set {
                this.containsDigitalDocumentsField = value;
            }
        }
        
        /// <remarks/>
        public bool searchRelatedOtherRecords {
            get {
                return this.searchRelatedOtherRecordsField;
            }
            set {
                this.searchRelatedOtherRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relatedRecordsName")]
        public string[] relatedRecordsName {
            get {
                return this.relatedRecordsNameField;
            }
            set {
                this.relatedRecordsNameField = value;
            }
        }
        
        /// <remarks/>
        public bool systemFileConcept {
            get {
                return this.systemFileConceptField;
            }
            set {
                this.systemFileConceptField = value;
            }
        }
        
        /// <remarks/>
        public bool multipleDataCollection {
            get {
                return this.multipleDataCollectionField;
            }
            set {
                this.multipleDataCollectionField = value;
            }
        }
        
        /// <remarks/>
        public bool personalDataRestrictedInfo {
            get {
                return this.personalDataRestrictedInfoField;
            }
            set {
                this.personalDataRestrictedInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool otherAccessTypeRestrictions {
            get {
                return this.otherAccessTypeRestrictionsField;
            }
            set {
                this.otherAccessTypeRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string archiveApproval {
            get {
                return this.archiveApprovalField;
            }
            set {
                this.archiveApprovalField = value;
            }
        }
        
        /// <remarks/>
        public string archiveRestrictions {
            get {
                return this.archiveRestrictionsField;
            }
            set {
                this.archiveRestrictionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class archiveIndexArchiveCreatorList {
        
        private string[] creatorNameField;
        
        private string[] creationPeriodStartField;
        
        private string[] creationPeriodEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creatorName")]
        public string[] creatorName {
            get {
                return this.creatorNameField;
            }
            set {
                this.creatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creationPeriodStart")]
        public string[] creationPeriodStart {
            get {
                return this.creationPeriodStartField;
            }
            set {
                this.creationPeriodStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creationPeriodEnd")]
        public string[] creationPeriodEnd {
            get {
                return this.creationPeriodEndField;
            }
            set {
                this.creationPeriodEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class archiveIndexForm {
        
        private string formVersionField;
        
        private archiveIndexFormClassList classListField;
        
        /// <remarks/>
        public string formVersion {
            get {
                return this.formVersionField;
            }
            set {
                this.formVersionField = value;
            }
        }
        
        /// <remarks/>
        public archiveIndexFormClassList classList {
            get {
                return this.classListField;
            }
            set {
                this.classListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class archiveIndexFormClassList {
        
        private string[] formClassField;
        
        private string[] formClassTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formClass")]
        public string[] formClass {
            get {
                return this.formClassField;
            }
            set {
                this.formClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("formClassText")]
        public string[] formClassText {
            get {
                return this.formClassTextField;
            }
            set {
                this.formClassTextField = value;
            }
        }
    }
}
