//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace NEA.ArchiveModel.BKG1007 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0", IsNullable=false)]
    public partial class contextDocumentationIndex {
        
        private contextDocumentationIndexDocument[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document")]
        public contextDocumentationIndexDocument[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class contextDocumentationIndexDocument {
        
        private string documentIDField;
        
        private string documentTitleField;
        
        private string documentDescriptionField;
        
        private string documentDateField;
        
        private contextDocumentationIndexDocumentDocumentAuthor[] documentAuthorField;
        
        private documentCategoryType documentCategoryField;
        
        /// <remarks/>
        public string documentID {
            get {
                return this.documentIDField;
            }
            set {
                this.documentIDField = value;
            }
        }
        
        /// <remarks/>
        public string documentTitle {
            get {
                return this.documentTitleField;
            }
            set {
                this.documentTitleField = value;
            }
        }
        
        /// <remarks/>
        public string documentDescription {
            get {
                return this.documentDescriptionField;
            }
            set {
                this.documentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string documentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentAuthor")]
        public contextDocumentationIndexDocumentDocumentAuthor[] documentAuthor {
            get {
                return this.documentAuthorField;
            }
            set {
                this.documentAuthorField = value;
            }
        }
        
        /// <remarks/>
        public documentCategoryType documentCategory {
            get {
                return this.documentCategoryField;
            }
            set {
                this.documentCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class contextDocumentationIndexDocumentDocumentAuthor {
        
        private string authorNameField;
        
        private string authorInstitutionField;
        
        /// <remarks/>
        public string authorName {
            get {
                return this.authorNameField;
            }
            set {
                this.authorNameField = value;
            }
        }
        
        /// <remarks/>
        public string authorInstitution {
            get {
                return this.authorInstitutionField;
            }
            set {
                this.authorInstitutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class informationOtherType {
        
        private bool informationOtherField;
        
        public informationOtherType() {
            this.informationOtherField = false;
        }
        
        /// <remarks/>
        public bool informationOther {
            get {
                return this.informationOtherField;
            }
            set {
                this.informationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class archivalPreservationInformationType {
        
        private bool archivalMigrationInformationField;
        
        private bool archivalInformationOtherField;
        
        public archivalPreservationInformationType() {
            this.archivalMigrationInformationField = false;
            this.archivalInformationOtherField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalMigrationInformation {
            get {
                return this.archivalMigrationInformationField;
            }
            set {
                this.archivalMigrationInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalInformationOther {
            get {
                return this.archivalInformationOtherField;
            }
            set {
                this.archivalInformationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class ingestInformationType {
        
        private bool archivistNotesField;
        
        private bool archivalTestNotesField;
        
        private bool archivalInformationOtherField;
        
        public ingestInformationType() {
            this.archivistNotesField = false;
            this.archivalTestNotesField = false;
            this.archivalInformationOtherField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivistNotes {
            get {
                return this.archivistNotesField;
            }
            set {
                this.archivistNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalTestNotes {
            get {
                return this.archivalTestNotesField;
            }
            set {
                this.archivalTestNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalInformationOther {
            get {
                return this.archivalInformationOtherField;
            }
            set {
                this.archivalInformationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class submissionInformationType {
        
        private bool archivalProvisionsField;
        
        private bool archivalTransformationInformationField;
        
        private bool archivalInformationOtherField;
        
        public submissionInformationType() {
            this.archivalProvisionsField = false;
            this.archivalTransformationInformationField = false;
            this.archivalInformationOtherField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalProvisions {
            get {
                return this.archivalProvisionsField;
            }
            set {
                this.archivalProvisionsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalTransformationInformation {
            get {
                return this.archivalTransformationInformationField;
            }
            set {
                this.archivalTransformationInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool archivalInformationOther {
            get {
                return this.archivalInformationOtherField;
            }
            set {
                this.archivalInformationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class operationalInformationType {
        
        private bool operationalSystemInformationField;
        
        private bool operationalSystemConvertedInformationField;
        
        private bool operationalSystemSOAField;
        
        private bool operationalSystemInformationOtherField;
        
        public operationalInformationType() {
            this.operationalSystemInformationField = false;
            this.operationalSystemConvertedInformationField = false;
            this.operationalSystemSOAField = false;
            this.operationalSystemInformationOtherField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool operationalSystemInformation {
            get {
                return this.operationalSystemInformationField;
            }
            set {
                this.operationalSystemInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool operationalSystemConvertedInformation {
            get {
                return this.operationalSystemConvertedInformationField;
            }
            set {
                this.operationalSystemConvertedInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool operationalSystemSOA {
            get {
                return this.operationalSystemSOAField;
            }
            set {
                this.operationalSystemSOAField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool operationalSystemInformationOther {
            get {
                return this.operationalSystemInformationOtherField;
            }
            set {
                this.operationalSystemInformationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class systemInformationType {
        
        private bool systemPurposeField;
        
        private bool systemRegulationsField;
        
        private bool systemContentField;
        
        private bool systemAdministrativeFunctionsField;
        
        private bool systemPresentationStructureField;
        
        private bool systemDataProvisionField;
        
        private bool systemDataTransferField;
        
        private bool systemPreviousSubsequentFunctionsField;
        
        private bool systemAgencyQualityControlField;
        
        private bool systemPublicationField;
        
        private bool systemInformationOtherField;
        
        public systemInformationType() {
            this.systemPurposeField = false;
            this.systemRegulationsField = false;
            this.systemContentField = false;
            this.systemAdministrativeFunctionsField = false;
            this.systemPresentationStructureField = false;
            this.systemDataProvisionField = false;
            this.systemDataTransferField = false;
            this.systemPreviousSubsequentFunctionsField = false;
            this.systemAgencyQualityControlField = false;
            this.systemPublicationField = false;
            this.systemInformationOtherField = false;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemPurpose {
            get {
                return this.systemPurposeField;
            }
            set {
                this.systemPurposeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemRegulations {
            get {
                return this.systemRegulationsField;
            }
            set {
                this.systemRegulationsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemContent {
            get {
                return this.systemContentField;
            }
            set {
                this.systemContentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemAdministrativeFunctions {
            get {
                return this.systemAdministrativeFunctionsField;
            }
            set {
                this.systemAdministrativeFunctionsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemPresentationStructure {
            get {
                return this.systemPresentationStructureField;
            }
            set {
                this.systemPresentationStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemDataProvision {
            get {
                return this.systemDataProvisionField;
            }
            set {
                this.systemDataProvisionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemDataTransfer {
            get {
                return this.systemDataTransferField;
            }
            set {
                this.systemDataTransferField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemPreviousSubsequentFunctions {
            get {
                return this.systemPreviousSubsequentFunctionsField;
            }
            set {
                this.systemPreviousSubsequentFunctionsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemAgencyQualityControl {
            get {
                return this.systemAgencyQualityControlField;
            }
            set {
                this.systemAgencyQualityControlField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemPublication {
            get {
                return this.systemPublicationField;
            }
            set {
                this.systemPublicationField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool systemInformationOther {
            get {
                return this.systemInformationOtherField;
            }
            set {
                this.systemInformationOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sa.dk/xmlns/diark/1.0")]
    public partial class documentCategoryType {
        
        private systemInformationType systemInformationField;
        
        private operationalInformationType operationalInformationField;
        
        private submissionInformationType submissionInformationField;
        
        private ingestInformationType ingestInformationField;
        
        private archivalPreservationInformationType archivalPreservationInformationField;
        
        private informationOtherType informationOtherField;
        
        /// <remarks/>
        public systemInformationType systemInformation {
            get {
                return this.systemInformationField;
            }
            set {
                this.systemInformationField = value;
            }
        }
        
        /// <remarks/>
        public operationalInformationType operationalInformation {
            get {
                return this.operationalInformationField;
            }
            set {
                this.operationalInformationField = value;
            }
        }
        
        /// <remarks/>
        public submissionInformationType submissionInformation {
            get {
                return this.submissionInformationField;
            }
            set {
                this.submissionInformationField = value;
            }
        }
        
        /// <remarks/>
        public ingestInformationType ingestInformation {
            get {
                return this.ingestInformationField;
            }
            set {
                this.ingestInformationField = value;
            }
        }
        
        /// <remarks/>
        public archivalPreservationInformationType archivalPreservationInformation {
            get {
                return this.archivalPreservationInformationField;
            }
            set {
                this.archivalPreservationInformationField = value;
            }
        }
        
        /// <remarks/>
        public informationOtherType informationOther {
            get {
                return this.informationOtherField;
            }
            set {
                this.informationOtherField = value;
            }
        }
    }
}
