// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HardHorn.Resources
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using HardHorn.Archiving;
    using HardHorn.ViewModels;
    using System.Windows.Data;
    using System.Web;
    using HardHorn.Utility;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class NotificationLog : NotificationLogBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!doctype html>\r\n<html>\r\n<head>\r\n<meta charset=\"UTF-8\">\r\n<meta name=\"viewport\" co" +
                    "ntent=\"width=device-width, initial-scale=1.0\">\r\n<style>\r\n\th1 { font-size: 1.5em;" +
                    " }\r\n\th2 { font-size: 1.25em; }\r\n\th3 { font-size: 1.0em;}\r\n\tbody { font-size: 0.8" +
                    "em; }\r\n\tth, td { padding: 2px; }\r\n\tth { text-align: left; white-space: nowrap; }" +
                    "\r\n\ttable { border-collapse: collapse; border-spacing: 0; }\r\n\t.sort {display:inli" +
                    "ne-block; width: 0; height: 0; border-left: 8px solid transparent; border-right:" +
                    " 8px solid transparent; }\r\n\t.expanded span  {margin: 0 0 3px 0; display:inline-b" +
                    "lock; border-top:  5px solid black; border-left: 5px solid transparent; border-r" +
                    "ight:  5px solid transparent; width: 0; height: 0; position: relative;}\r\n\t.colla" +
                    "psed span {margin: 0 0 0 3px; display:inline-block; border-left: 5px solid black" +
                    "; border-top:  5px solid transparent; border-bottom: 5px solid transparent; widt" +
                    "h: 0; height: 0; position: relative;}\r\n\t.expander {cursor:pointer;}\r\n\t.sortable " +
                    "{cursor:pointer;}\r\n\t.asc {border-bottom: 10px solid black;}\r\n\t.desc {border-top:" +
                    " 10px solid black;}\r\n\t.value {font-family: \"Lucida Console\", Monaco, monospace;}" +
                    "\r\n\t.empty {font-weight: bold; color: brown;}\r\n\t.null {font-weight: bold; color: " +
                    "blue;}\r\n\t.samples-table {margin: 0 0.8em 0.8em 0.8em; font-size: 0.7em;}\r\n\t.odd," +
                    " .odd + .samplerow {background: #f5f5f5}\r\n\t.odd > td:nth-child(even) { backgroun" +
                    "d: #f6f6f6; }\r\n\t.even > td-nth-child(odd) { background: #fdfdfd; }\r\n\t.samples-ta" +
                    "ble > tbody > tr:nth-child(odd) { background: #f5f5f5;}\r\n\t.samples-table > tbody" +
                    " > tr:nth-child(even) { background: #ffffff;}\r\n\t.samples-table > tbody > tr:nth-" +
                    "child(odd) > td:nth-child(even) { background: #f6f6f6;}\r\n\t.samples-table > tbody" +
                    " > tr:nth-child(even) > td:nth-child(odd) { background: #fdfdfd;}\r\n\t.header-acti" +
                    "ons {font-weight: normal; font-size: 0.8em;}\r\n</style>\r\n<script>\r\n\tfunction togg" +
                    "leSamples(sender, sampleRow) {\r\n\t\tif (sampleRow.style.display === \'none\')\r\n\t\t{\r\n" +
                    "\t\t\tsampleRow.style.display = \'table-row\';\r\n\t\t\tsender.classList = \"expander expan" +
                    "ded\";\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tsampleRow.style.display = \'none\';\r\n\t\t\tsender.classLi" +
                    "st = \"expander collapsed\";\r\n\t\t}\r\n\t}\r\n\r\n\tfunction expandAll(container)\r\n\t{\r\n\t\tvar" +
                    " elems = Array.prototype.slice.call(container.getElementsByClassName(\'collapsed\'" +
                    "));\r\n\t\tfor (var i = 0; i < elems.length; i++) {\r\n\t\t\telems[i].onclick();\r\n\t\t}\r\n\t}" +
                    "\r\n\r\n\tfunction collapseAll(container)\r\n\t{\r\n\t\tvar elems = Array.prototype.slice.ca" +
                    "ll(container.getElementsByClassName(\'expanded\'));\r\n\t\tfor (var i = 0; i < elems.l" +
                    "ength; i++) {\r\n\t\t\telems[i].onclick();\r\n\t\t}\r\n\t}\r\n\r\n\tfunction sortBy(sender, table" +
                    ", sortColumnIndex) {\r\n\t\tvar sortTypeElem = table.children[0].children[0].childre" +
                    "n[sortColumnIndex].getElementsByTagName(\'strong\')[0];\r\n\t\tvar sortType = \'\';\r\n\t\ti" +
                    "f (sortTypeElem != undefined) {\r\n\t\t\tsortType = sortTypeElem.innerText;\r\n\t\t}\r\n\t\tv" +
                    "ar rows = [];\r\n\t\tvar trs = table.children[1].children;\r\n\t\tfor (var i = 0; i < tr" +
                    "s.length; i++) {\r\n\t\t\tif (trs[i].classList == \"samplerow\")\r\n\t\t\t{\r\n\t\t\t\trows[rows.l" +
                    "ength-1].sampleRow = trs[i];\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\trows.push(trs[i]);\r\n\t\t\t}\r" +
                    "\n\t\t}\r\n\t\tvar glyphs = table.getElementsByClassName(\'sort\');\r\n\t\tfor (var i = 0; i " +
                    "< glyphs.length; i++) {\r\n\t\t\tglyphs[i].remove();\r\n\t\t}\r\n\t\tif (table.lastSortType =" +
                    "= sortType) {\r\n\t\t\ttable.sortAscending = !table.sortAscending;\r\n\t\t\trows.reverse()" +
                    ";\r\n\t\t} else {\r\n\t\t\ttable.sortAscending = true;\r\n\t\t\ttable.lastSortType = sortType;" +
                    "\r\n\t\t\trows.sort(getSortFunc(sortType, sortColumnIndex)); \r\n\t\t}\r\n\t\taddGlyph(table," +
                    " sortColumnIndex);\r\n\t\treaddRows(rows);\r\n\t}\r\n\r\n\tfunction getSortFunc(sortType, so" +
                    "rtColumnIndex) {\r\n\tswitch (sortType) {\r\n\t\tcase \'Felt\':\r\n\t\t\treturn function(row1," +
                    " row2) {\r\n\t\t\t\tvar idx = sortColumnIndex;\r\n\t\t\t\tvar field1 = row1.children[idx].in" +
                    "nerText;\r\n\t\t\t\tvar field2 = row2.children[idx].innerText;\r\n\t\t\t\tif (field1 == \'-\')" +
                    " {\r\n\t\t\t\t\treturn -1;\r\n\t\t\t\t}\r\n\t\t\t\tif (field2 == \'-\') {\r\n\t\t\t\t\treturn 1;\r\n\t\t\t\t}\r\n\t\t\t" +
                    "\tvar f1 = parseInt(field1.substr(2, field1.indexOf(\':\')-2));\r\n\t\t\t\tvar f2 = parse" +
                    "Int(field2.substr(2, field2.indexOf(\':\')-2));\r\n\t\t\t\treturn f1-f2;\r\n\t\t\t};\r\n\t\t\tbrea" +
                    "k;\r\n\t\tcase \'Tabel\':\r\n\t\t\treturn function(row1, row2) {\r\n\t\t\t\tvar idx = sortColumnI" +
                    "ndex;\r\n\t\t\t\tvar field1 = row1.children[idx].innerText;\r\n\t\t\t\tvar field2 = row2.chi" +
                    "ldren[idx].innerText;\r\n\t\t\t\tif (field1 == \'-\') {\r\n\t\t\t\t\treturn -1;\r\n\t\t\t\t}\r\n\t\t\t\tif " +
                    "(field2 == \'-\') {\r\n\t\t\t\t\treturn 1;\r\n\t\t\t\t}\r\n\t\t\t\tvar f1 = parseInt(field1.substr(6," +
                    " field1.indexOf(\':\')-6));\r\n\t\t\t\tvar f2 = parseInt(field2.substr(6, field2.indexOf" +
                    "(\':\')-6));\r\n\t\t\t\treturn f1-f2;\r\n\t\t\t};\r\n\t\t\tbreak;\r\n\t\tcase \'Række\':\r\n\t\tcase \'Antal\'" +
                    ":\r\n\t\tcase \'Forekomster\':\r\n\t\t\treturn function(row1, row2) {\r\n\t\t\t\tvar idx = sortCo" +
                    "lumnIndex;\r\n\t\t\t\tvar field1 = row1.children[idx].innerText;\r\n\t\t\t\tvar field2 = row" +
                    "2.children[idx].innerText;\r\n\t\t\t\tif (field1 == \'-\') {\r\n\t\t\t\t\treturn -1;\r\n\t\t\t\t}\r\n\t\t" +
                    "\t\tif (field2 == \'-\') {\r\n\t\t\t\t\treturn 1;\r\n\t\t\t\t}\r\n\t\t\t\treturn parseInt(field1) - par" +
                    "seInt(field2);\r\n\t\t\t};\r\n\t\t\tbreak;\r\n\t\tdefault:\r\n\t\t\treturn function(row1, row2) {\r\n" +
                    "\t\t\t\tvar idx = sortColumnIndex;\r\n\t\t\t\tvar field1 = row1.children[idx].innerText;\r\n" +
                    "\t\t\t\tvar field2 = row2.children[idx].innerText;\r\n\t\t\t\tif (field1 == \'-\') {\r\n\t\t\t\t\tr" +
                    "eturn -1;\r\n\t\t\t\t}\r\n\t\t\t\tif (field2 == \'-\') {\r\n\t\t\t\t\treturn 1;\r\n\t\t\t\t}\r\n\t\t\t\treturn fi" +
                    "eld1.localeCompare(field2);\r\n\t\t\t};\r\n\t\t\tbreak;\r\n\t\t}\r\n\t}\r\n\r\n\tfunction readdRows(ro" +
                    "ws) {\r\n\t\tfor (var i = 0; i < rows.length; i++) {\r\n\t\t\tvar parent = rows[i].parent" +
                    "Node;\r\n\t\t\tvar detached = parent.removeChild(rows[i]);\r\n\t\t\tif (detached.sampleRow" +
                    ")\r\n\t\t\t{\r\n\t\t\t\tparent.removeChild(detached.sampleRow);\r\n\t\t\t}\r\n\t\t\tif (i % 2 == 0) {" +
                    "\r\n\t\t\t\tdetached.classList.replace(\'even\', \'odd\');\r\n\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n\t\t\t\tdetac" +
                    "hed.classList.replace(\'odd\', \'even\');\r\n\t\t\t}\r\n\t\t\tparent.appendChild(detached); \r\n" +
                    "\t\t\tif (detached.sampleRow)\r\n\t\t\t{\r\n\t\t\t\tparent.appendChild(detached.sampleRow);\r\n\t" +
                    "\t\t}\r\n\t\t}\r\n\t}\r\n\r\n\tfunction addGlyph(table, columnIndex) {\r\n\t\tvar glyph = document" +
                    ".createElement(\'span\');\r\n\t\tglyph.classList.add(\'sort\');\r\n\t\tif (table.sortAscendi" +
                    "ng) {\r\n\t\t\tglyph.classList.add(\'asc\');\r\n\t\t} else {\r\n\t\t\tglyph.classList.add(\'desc\'" +
                    ");\r\n\t\t}\r\n\t\ttable.children[0].children[0].children[columnIndex].appendChild(glyph" +
                    ");\r\n\t}\r\n</script>\r\n<title>");
            
            #line 209 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ArchiveVersion.Id));
            
            #line default
            #line hidden
            this.Write(" - ");
            
            #line 209 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(System.Reflection.Assembly.GetExecutingAssembly().GetName().Name));
            
            #line default
            #line hidden
            this.Write(" Log</title>\r\n</head>\r\n<body style=\"font-family: verdana, sans-serif;\">\r\n<h1>");
            
            #line 212 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ArchiveVersion.Id));
            
            #line default
            #line hidden
            this.Write(" - ");
            
            #line 212 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(System.Reflection.Assembly.GetExecutingAssembly().GetName().Name));
            
            #line default
            #line hidden
            this.Write(" Log</h1>\r\n<p><strong>Tidspunkt:</strong> ");
            
            #line 213 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now));
            
            #line default
            #line hidden
            this.Write("</p>\r\n<h2 id=\"oversigt\">Oversigt</h2>\r\n<ul>\r\n");
            
            #line 216 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

foreach (CollectionViewGroup group in NotificationGroups)
{
	string groupNameEncoded = HttpUtility.HtmlEncode(group.Name);

            
            #line default
            #line hidden
            this.Write("    <li><a href=\"#");
            
            #line 221 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 221 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 221 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(group.ItemCount));
            
            #line default
            #line hidden
            this.Write(" punkter)</a></li>\r\n");
            
            #line 222 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

}

            
            #line default
            #line hidden
            this.Write("</ul>\r\n<h2>Rapport</h2>\r\n");
            
            #line 227 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

foreach (CollectionViewGroup group in NotificationGroups)
{
	string groupNameEncoded = HttpUtility.HtmlEncode(group.Name);

            
            #line default
            #line hidden
            this.Write("    <div id=\"");
            
            #line 232 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("\">\r\n        <h3>\r\n\t\t\t");
            
            #line 234 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("&nbsp;<span class=\"header-actions\"><a href=\"#oversigt\">[til oversigt]</a> <a href" +
                    "=\"javascript:void(0)\" onclick=\"expandAll(document.getElementById(\'");
            
            #line 234 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("\'))\">[udvid eksempler]</a> <a href=\"javascript:void(0)\" onclick=\"collapseAll(docu" +
                    "ment.getElementById(\'");
            
            #line 234 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("\'))\">[sammenfold eksempler]</a></span>\r\n\t\t</h3>\r\n        <table class=\"notificati" +
                    "ons-table\" id=\"");
            
            #line 236 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));
            
            #line default
            #line hidden
            this.Write("_table\">\r\n\t\t\t<thead>\r\n");
            
            #line 238 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	OutputNotificationHeaderRow(groupNameEncoded);

            
            #line default
            #line hidden
            this.Write("\t\t\t</thead>\r\n\t\t\t<tbody>\r\n");
            
            #line 243 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	int index = 0;
	foreach (INotification notification in group.Items)
	{
		OutputNotificationRow(notification, ++index % 2 == 0);
    }

            
            #line default
            #line hidden
            this.Write("\t\t\t</tbody>\r\n\t\t</table>\r\n\t</div>\r\n");
            
            #line 253 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

}

            
            #line default
            #line hidden
            this.Write("</body>\r\n</html>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 259 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

private void OutputNotificationHeaderRow(string groupNameEncoded)
{

        
        #line default
        #line hidden
        
        #line 262 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t<tr>\r\n\t\t\t\t<th></th>\r\n\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.g" +
        "etElementById(\'");

        
        #line default
        #line hidden
        
        #line 265 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 265 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 1)\"></th>\r\n");

        
        #line default
        #line hidden
        
        #line 266 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	if (!GroupByTables)
	{

        
        #line default
        #line hidden
        
        #line 269 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 270 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 270 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 2)\">\r\n\t\t\t\t\t<strong>Tabel</strong>\r\n\t\t\t\t</th>\r\n");

        
        #line default
        #line hidden
        
        #line 273 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 275 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 276 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 2)\">\r\n\t\t\t\t\t<strong>Felt</strong>\r\n\t\t\t\t</th>\r\n");

        
        #line default
        #line hidden
        
        #line 279 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	if (GroupByTables)
	{

        
        #line default
        #line hidden
        
        #line 282 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 283 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 283 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 3)\">\r\n\t\t\t\t\t<strong>Kategori</strong>\r\n\t\t\t\t</th>\r\n");

        
        #line default
        #line hidden
        
        #line 286 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 288 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 289 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 289 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 4)\">\r\n\t\t\t\t\t<strong>Forekomster</strong>\r\n\t\t\t\t</th>\r\n\t\t\t\t<th class=\"sort" +
        "able\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 292 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(groupNameEncoded));

        
        #line default
        #line hidden
        
        #line 292 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_table\'), 5)\">\r\n\t\t\t\t\t<strong>Besked</strong>\r\n\t\t\t\t</th>\r\n\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 296 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

}

private void OutputNotificationRow(INotification notification, bool even)
{
	if (even) 
	{

        
        #line default
        #line hidden
        
        #line 303 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t<tr class=\"even\">\r\n");

        
        #line default
        #line hidden
        
        #line 305 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	} 
	else 
	{

        
        #line default
        #line hidden
        
        #line 309 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t<tr class=\"odd\">\r\n");

        
        #line default
        #line hidden
        
        #line 311 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}
	if (AnalysisErrorSamples.ContainsKey(notification))
	{

        
        #line default
        #line hidden
        
        #line 315 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td class=\"expander expanded\" onclick=\"toggleSamples(this, document.getElemen" +
        "tById(\'");

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Table.Folder));

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Column.ColumnId));

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Type));

        
        #line default
        #line hidden
        
        #line 316 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow\'))\"><span></span></td>\r\n");

        
        #line default
        #line hidden
        
        #line 317 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}
	else if (notification.Type == NotificationType.ForeignKeyTestError)
	{
		ForeignKey fkey = (notification as NotificationViewModel).ForeignKey;

        
        #line default
        #line hidden
        
        #line 322 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td class=\"expander expanded\" onclick=\"toggleSamples(this, document.getElemen" +
        "tById(\'");

        
        #line default
        #line hidden
        
        #line 323 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));

        
        #line default
        #line hidden
        
        #line 323 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow\'))\"><span></span></td>\r\n");

        
        #line default
        #line hidden
        
        #line 324 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}
	else
	{

        
        #line default
        #line hidden
        
        #line 328 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td></td>\r\n");

        
        #line default
        #line hidden
        
        #line 330 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 332 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td>\r\n");

        
        #line default
        #line hidden
        
        #line 334 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	if (notification.Severity == Severity.Hint)
	{

        
        #line default
        #line hidden
        
        #line 337 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t<b style=\"background: yellow;\">!</b>\r\n");

        
        #line default
        #line hidden
        
        #line 339 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}
	else 
	{

        
        #line default
        #line hidden
        
        #line 343 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t<b style=\"background: red; color: white;\">X</b>\r\n");

        
        #line default
        #line hidden
        
        #line 345 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 347 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 349 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	if (!GroupByTables)
	{

        
        #line default
        #line hidden
        
        #line 352 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td>\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 354 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(HttpUtility.HtmlEncode(notification.Table?.ToString() ?? "-")));

        
        #line default
        #line hidden
        
        #line 354 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 356 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 358 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td>\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 360 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(HttpUtility.HtmlEncode(notification.Column?.ToString() ?? "-")));

        
        #line default
        #line hidden
        
        #line 360 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 362 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	if (GroupByTables)
	{

        
        #line default
        #line hidden
        
        #line 365 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td>\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 367 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(HttpUtility.HtmlEncode(NotificationsUtility.NotificationTypeToString(notification.Type)?.ToString() ?? "-")));

        
        #line default
        #line hidden
        
        #line 367 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 369 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	}

        
        #line default
        #line hidden
        
        #line 371 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t<td>\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 373 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Count?.ToString() ?? "-"));

        
        #line default
        #line hidden
        
        #line 373 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 376 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(HttpUtility.HtmlEncode(notification.Message?.ToString() ?? "-")));

        
        #line default
        #line hidden
        
        #line 376 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t</td>\r\n            </tr>\r\n");

        
        #line default
        #line hidden
        
        #line 379 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	switch (notification.Type)
	{
		case NotificationType.AnalysisErrorBlank:
        case NotificationType.AnalysisErrorOverflow:
        case NotificationType.AnalysisErrorUnderflow:
        case NotificationType.AnalysisErrorFormat:
        case NotificationType.AnalysisErrorRegex:
        case NotificationType.AnalysisErrorRepeatingChar:
        case NotificationType.AnalysisErrorUnallowedKeyword:
			OutputAnalysisSamples(notification);
			break;
		case NotificationType.ForeignKeyTestError:
			OutputForeignKeyTestErrorSamples(notification);
			break;
	}
}

private void OutputAnalysisSamples(INotification notification)
{


        
        #line default
        #line hidden
        
        #line 400 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("            <tr id=\"");

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Table.Folder));

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Column.ColumnId));

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Type));

        
        #line default
        #line hidden
        
        #line 401 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow\" class=\"samplerow\">\r\n\t\t\t\t<td colspan=\"6\">\r\n\t\t\t\t<table class=\"samples-t" +
        "able\" id=\"");

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Table.Folder));

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Column.ColumnId));

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Type));

        
        #line default
        #line hidden
        
        #line 403 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\">\r\n\t\t\t\t\t<thead>\r\n\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<th class=\"sortable\" o" +
        "nclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Table.Folder));

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Column.ColumnId));

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Type));

        
        #line default
        #line hidden
        
        #line 407 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\'), 0)\">\r\n\t\t\t\t\t\t\t<strong>Række</strong>\r\n\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t</th " +
        "onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Table.Folder));

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Column.ColumnId));

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_");

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(notification.Type));

        
        #line default
        #line hidden
        
        #line 410 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\'), 0)\">\r\n\t\t\t\t\t\t\t<strong>Data</strong>\r\n\t\t\t\t\t\t</th>\r\n\t\t\t\t\t</tr>\r\n" +
        "\t\t\t\t\t</thead>\r\n\t\t\t\t\t<tbody>\r\n");

        
        #line default
        #line hidden
        
        #line 416 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	foreach (var post in AnalysisErrorSamples[notification])
	{

        
        #line default
        #line hidden
        
        #line 419 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 422 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(post.RowIndex + 1));

        
        #line default
        #line hidden
        
        #line 422 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t<p class=\"data\">");

        
        #line default
        #line hidden
        
        #line 425 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(post.Data));

        
        #line default
        #line hidden
        
        #line 425 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("</p>\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 428 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	} // foreach post

        
        #line default
        #line hidden
        
        #line 430 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t</tbody>\r\n\t\t\t\t</table>\r\n\t\t\t\t</td>\r\n            </tr>\r\n");

        
        #line default
        #line hidden
        
        #line 435 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

}

private void OutputForeignKeyTestErrorSamples(INotification notification)
{
	ForeignKey fkey = (notification as NotificationViewModel).ForeignKey;


        
        #line default
        #line hidden
        
        #line 442 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("            <tr id=\"");

        
        #line default
        #line hidden
        
        #line 443 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));

        
        #line default
        #line hidden
        
        #line 443 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow\" class=\"samplerow\">\r\n\t\t\t\t<td colspan=\"6\">\r\n\t\t\t\t\t<table class=\"samples-" +
        "table\" id=\"");

        
        #line default
        #line hidden
        
        #line 445 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));

        
        #line default
        #line hidden
        
        #line 445 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\">\r\n\t\t\t\t\t\t<thead>\r\n\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t<th class=\"sortable\" onclic" +
        "k=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 448 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));

        
        #line default
        #line hidden
        
        #line 448 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\'), 0)\">\r\n\t\t\t\t\t\t\t\t<strong>Antal</strong>\r\n\t\t\t\t\t\t\t</th>\r\n");

        
        #line default
        #line hidden
        
        #line 451 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

		int colidx = 1;
		foreach (var reference in fkey.References)
		{

        
        #line default
        #line hidden
        
        #line 455 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t<th class=\"sortable\" onclick=\"sortBy(this, document.getElementById(\'");

        
        #line default
        #line hidden
        
        #line 456 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(fkey.Name));

        
        #line default
        #line hidden
        
        #line 456 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("_samplerow_table\'), ");

        
        #line default
        #line hidden
        
        #line 456 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(colidx));

        
        #line default
        #line hidden
        
        #line 456 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(")\">\r\n\t\t\t\t\t\t\t\t<strong>");

        
        #line default
        #line hidden
        
        #line 457 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(HttpUtility.HtmlEncode(reference.Column.Name)));

        
        #line default
        #line hidden
        
        #line 457 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("</strong>\r\n\t\t\t\t\t\t\t</th>\r\n");

        
        #line default
        #line hidden
        
        #line 459 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

			colidx++;
		}

        
        #line default
        #line hidden
        
        #line 462 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t</thead>\r\n\t\t\t\t\t\t<tbody>\r\n");

        
        #line default
        #line hidden
        
        #line 466 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"


	foreach (var sample in ForeignKeyErrorSamples[fkey])
	{
		var values = sample.Item1.Values;
		var count = sample.Item2;

        
        #line default
        #line hidden
        
        #line 472 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t");

        
        #line default
        #line hidden
        
        #line 475 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(count));

        
        #line default
        #line hidden
        
        #line 475 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\r\n\t\t\t\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 477 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

		foreach (Post post in sample.Item1.Values)
		{

        
        #line default
        #line hidden
        
        #line 480 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t<td>\r\n");

        
        #line default
        #line hidden
        
        #line 482 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

			if (post.IsNull)
			{

        
        #line default
        #line hidden
        
        #line 485 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t\t<span class=\"value null\">NULL</span>\r\n");

        
        #line default
        #line hidden
        
        #line 487 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

			}
			else if (post.Data == string.Empty)
			{

        
        #line default
        #line hidden
        
        #line 491 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t\t<span class=\"value empty\">TOM</span>\r\n");

        
        #line default
        #line hidden
        
        #line 493 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

			}
			else
			{

        
        #line default
        #line hidden
        
        #line 497 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t\t<span class=\"value\">");

        
        #line default
        #line hidden
        
        #line 498 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(post.Data));

        
        #line default
        #line hidden
        
        #line 498 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("</span>\r\n");

        
        #line default
        #line hidden
        
        #line 499 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

			}

        
        #line default
        #line hidden
        
        #line 501 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t\t</td>\r\n");

        
        #line default
        #line hidden
        
        #line 503 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

		} // foreach post

        
        #line default
        #line hidden
        
        #line 505 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t</tr>\r\n");

        
        #line default
        #line hidden
        
        #line 507 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

	} // foreach sample

        
        #line default
        #line hidden
        
        #line 509 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"
this.Write("\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t</table>\r\n\t\t\t\t</td>\r\n            </tr>\r\n");

        
        #line default
        #line hidden
        
        #line 514 "C:\Users\EG5S\Source\Repos\TableDataAnalyzer\HardHornLight\Resources\NotificationLog.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class NotificationLogBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
